steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'custom-yarn', '.']
  id: 'prepare'

- name: 'custom-yarn'
  args: ['install']
  dir: 'image'
  id: 'image-install'
  waitFor: ['prepare']

- name: 'custom-yarn'
  args: ['install']
  dir: 'pose'
  id: 'pose-install'
  waitFor: ['prepare']

- name: 'custom-yarn'
  args: ['install']
  dir: 'audio'
  id: 'audio-install'
  waitFor: ['prepare']


- name: 'custom-yarn'
  args: ['run', 'build']
  dir: 'image'

- name: 'custom-yarn'
  args: ['run', 'test']
  dir: 'image'
  